-- Up Migration

CREATE TYPE admin_role AS ENUM ('OWNER', 'OPERATOR', 'ACCOUNTANT');

CREATE TYPE supplier_type AS ENUM ('REGISTERED', 'EXTERNAL', 'NONE');

CREATE TYPE order_state AS ENUM (
  'DRAFT', 'SUBMITTED',
  'REVIEW_PENDING', 'REVIEW_NEEDS_EDIT', 'REVIEW_APPROVED', 'REVIEW_REJECTED',
  'SUPPLIER_CHOICE',
  'EXT_VETTING_DOCS', 'EXT_VETTING_APPROVED', 'EXT_VETTING_REJECTED',
  'REG_PUBLISHED', 'REG_BIDS_COLLECTING', 'REG_BIDS_EXPIRED_NO_OFFERS',
  'REG_ADMIN_REVIEW_BIDS', 'REG_SHOWN_TO_CUSTOMER', 'REG_CUSTOMER_SELECTS',
  'REG_NO_OFFER_SELECTED',
  'CONTRACT_PAYMENT_PLAN_CREATED', 'CONTRACT_SIGNED', 'CONTRACT_BANK_TRANSFER_DONE',
  'CONTRACT_RECEIPT_UPLOADED', 'CONTRACT_ADMIN_VERIFYING', 'CONTRACT_RECEIPT_REJECTED',
  'IDENTITY_REVEALED',
  'PAYMENT_PENDING_SUPPLIER_ACK', 'PAYMENT_PENDING_ADMIN_VERIFICATION',
  'SUPPLIER_PAYMENT_CONFIRMED',
  'PROD_DESIGN_SUBMITTED', 'PROD_CHECKPOINT_1', 'PROD_CHECKPOINT_1_REJECTED',
  'PROD_FULL_PRODUCTION', 'PROD_QC_SUBMITTED', 'PROD_CHECKPOINT_2', 'PROD_CHECKPOINT_2_REJECTED',
  'ESCALATION_REMINDER', 'ESCALATION_ESCALATED',
  'AGREEMENT_CANCELLED_PENDING_RENEWAL',
  'RENEWAL_PENDING_SUPPLIER', 'RENEWAL_PENDING_ADMIN', 'RENEWAL_SUPPLIER_DECLINED',
  'LOGISTICS_ONLY_SETUP',
  'LOADING_SHIPPING', 'SHIPPING_DOCS', 'PAYMENT_INSTALLMENTS_PENDING',
  'IN_TRANSIT', 'ARRIVED_PORT',
  'CUSTOMS_FEE_ADDED', 'CUSTOMS_CUSTOMER_PAYS', 'CUSTOMS_FEE_PROOF_UPLOADED', 'CUSTOMS_FEE_VERIFIED',
  'FINAL_DELIVERY', 'CUSTOMER_SIGNED', 'SUPPLIER_RATED', 'COMPLETED',
  'DISPUTE_PAYMENT', 'DISPUTE_QUALITY', 'DISPUTE_DELAY', 'DISPUTE_SHIPPING',
  'DISPUTE_MANDATORY_REFUND', 'DISPUTE_RESOLVED',
  'CANCELLED'
);

CREATE TYPE hold_type AS ENUM ('NONE', 'ESCALATION', 'DISPUTE');

CREATE TYPE escalation_actor AS ENUM ('CUSTOMER_APPROVAL', 'SUPPLIER_DELIVERABLE');

CREATE TYPE dispute_type AS ENUM ('PAYMENT', 'QUALITY', 'DELAY', 'SHIPPING', 'MANDATORY_REFUND');

CREATE TYPE dispute_status AS ENUM ('OPEN', 'RESOLVED');

CREATE TYPE refund_policy AS ENUM ('NEVER_REFUNDABLE', 'REFUNDABLE_UNTIL_EVENT', 'REFUNDABLE_BY_DISPUTE_ONLY');

CREATE TYPE refundability_status AS ENUM ('REFUNDABLE', 'LOCKED');

CREATE TYPE contract_type AS ENUM ('STANDARD', 'LOGISTICS_ONLY');

CREATE TYPE customs_fee_status AS ENUM ('DRAFT', 'PUBLISHED', 'PAID', 'VERIFIED');

CREATE TYPE rating_phase AS ENUM ('PRE_CONTRACT', 'POST_CONTRACT');

CREATE TYPE vetting_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

CREATE TYPE renewal_decision AS ENUM ('PENDING', 'APPROVED', 'DECLINED');

-- Down Migration

DROP TYPE IF EXISTS renewal_decision;
DROP TYPE IF EXISTS vetting_status;
DROP TYPE IF EXISTS rating_phase;
DROP TYPE IF EXISTS customs_fee_status;
DROP TYPE IF EXISTS contract_type;
DROP TYPE IF EXISTS refundability_status;
DROP TYPE IF EXISTS refund_policy;
DROP TYPE IF EXISTS dispute_status;
DROP TYPE IF EXISTS dispute_type;
DROP TYPE IF EXISTS escalation_actor;
DROP TYPE IF EXISTS hold_type;
DROP TYPE IF EXISTS order_state;
DROP TYPE IF EXISTS supplier_type;
DROP TYPE IF EXISTS admin_role;
