/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AdminRole = "ACCOUNTANT" | "OPERATOR" | "OWNER";

export type ContractType = "LOGISTICS_ONLY" | "STANDARD";

export type CustomsFeeStatus = "DRAFT" | "PAID" | "PUBLISHED" | "VERIFIED";

export type DisputeStatus = "OPEN" | "RESOLVED";

export type DisputeType = "DELAY" | "MANDATORY_REFUND" | "PAYMENT" | "QUALITY" | "SHIPPING";

export type EscalationActor = "CUSTOMER_APPROVAL" | "SUPPLIER_DELIVERABLE";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type HoldType = "DISPUTE" | "ESCALATION" | "NONE" | "RENEWAL";

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type OrderState = "AGREEMENT_CANCELLED_PENDING_RENEWAL" | "ARRIVED_PORT" | "CANCELLED" | "COMPLETED" | "CONTRACT_ADMIN_VERIFYING" | "CONTRACT_BANK_TRANSFER_DONE" | "CONTRACT_PAYMENT_PLAN_CREATED" | "CONTRACT_RECEIPT_REJECTED" | "CONTRACT_RECEIPT_UPLOADED" | "CONTRACT_SIGNED" | "CUSTOMER_SIGNED" | "CUSTOMS_CUSTOMER_PAYS" | "CUSTOMS_FEE_ADDED" | "CUSTOMS_FEE_PROOF_UPLOADED" | "CUSTOMS_FEE_VERIFIED" | "DISPUTE_DELAY" | "DISPUTE_MANDATORY_REFUND" | "DISPUTE_PAYMENT" | "DISPUTE_QUALITY" | "DISPUTE_RESOLVED" | "DISPUTE_SHIPPING" | "DRAFT" | "ESCALATION_ESCALATED" | "ESCALATION_REMINDER" | "EXT_VETTING_APPROVED" | "EXT_VETTING_DOCS" | "EXT_VETTING_REJECTED" | "FINAL_DELIVERY" | "IDENTITY_REVEALED" | "IN_TRANSIT" | "LOADING_SHIPPING" | "LOGISTICS_ONLY_SETUP" | "PAYMENT_INSTALLMENTS_PENDING" | "PAYMENT_PENDING_ADMIN_VERIFICATION" | "PAYMENT_PENDING_SUPPLIER_ACK" | "PROD_CHECKPOINT_1" | "PROD_CHECKPOINT_1_REJECTED" | "PROD_CHECKPOINT_2" | "PROD_CHECKPOINT_2_REJECTED" | "PROD_DESIGN_SUBMITTED" | "PROD_FULL_PRODUCTION" | "PROD_QC_SUBMITTED" | "REG_ADMIN_REVIEW_BIDS" | "REG_BIDS_COLLECTING" | "REG_BIDS_EXPIRED_NO_OFFERS" | "REG_CUSTOMER_SELECTS" | "REG_NO_OFFER_SELECTED" | "REG_PUBLISHED" | "REG_SHOWN_TO_CUSTOMER" | "RENEWAL_PENDING_ADMIN" | "RENEWAL_PENDING_SUPPLIER" | "RENEWAL_SUPPLIER_DECLINED" | "REVIEW_APPROVED" | "REVIEW_NEEDS_EDIT" | "REVIEW_PENDING" | "REVIEW_REJECTED" | "SHIPPING_DOCS" | "SUBMITTED" | "SUPPLIER_CHOICE" | "SUPPLIER_PAYMENT_CONFIRMED" | "SUPPLIER_RATED";

export type RatingPhase = "POST_CONTRACT" | "PRE_CONTRACT";

export type RefundabilityStatus = "LOCKED" | "REFUNDABLE";

export type RefundPolicy = "NEVER_REFUNDABLE" | "REFUNDABLE_BY_DISPUTE_ONLY" | "REFUNDABLE_UNTIL_EVENT";

export type RenewalDecision = "APPROVED" | "DECLINED" | "PENDING";

export type SupplierType = "EXTERNAL" | "NONE" | "REGISTERED";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type VettingStatus = "APPROVED" | "PENDING" | "REJECTED";

export interface AdminUser {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  mfa_enabled: Generated<boolean>;
  name: string;
  role: AdminRole;
}

export interface AgreementRenewal {
  admin_decided_at: Timestamp | null;
  admin_decided_by: string | null;
  admin_decision: Generated<RenewalDecision>;
  id: Generated<string>;
  order_id: string;
  renewal_of_agreement_id: string | null;
  requested_at: Generated<Timestamp>;
  supplier_decided_at: Timestamp | null;
  supplier_decision: Generated<RenewalDecision>;
}

export interface AuditLog {
  action: string;
  actor_id: string | null;
  actor_role: string;
  entity_id: string;
  entity_type: string;
  id: Generated<Int8>;
  ip_address: string | null;
  occurred_at: Generated<Timestamp>;
  prev_hash: string | null;
  record_hash: string;
  state_after: Json | null;
  state_before: Json | null;
}

export interface BiddingBoard {
  created_at: Timestamp | null;
  fob_value_usd: Numeric | null;
  order_id: string | null;
  service_type_id: string | null;
}

export interface CompanyExpense {
  amount_sar: Numeric;
  category: string;
  id: Generated<string>;
  incurred_at: Timestamp;
  notes: string | null;
}

export interface Contract {
  id: Generated<string>;
  order_id: string;
  signature_ref: string | null;
  signed_at: Timestamp | null;
  terms_snapshot: Json;
  type: Generated<ContractType>;
}

export interface Customer {
  company_name: string | null;
  cr_number: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string;
  phone: string;
}

export interface CustomsFee {
  amount_sar: Numeric;
  approved_by: string | null;
  created_by: string;
  id: Generated<string>;
  label: string;
  linked_payment_id: string | null;
  order_id: string;
  status: Generated<CustomsFeeStatus>;
}

export interface Dispute {
  id: Generated<string>;
  opened_at: Generated<Timestamp>;
  opened_by_role: string;
  order_id: string;
  resolution_notes: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  resume_target_state_snapshot: string | null;
  status: Generated<DisputeStatus>;
  type: DisputeType;
}

export interface DisputeClaim {
  description: string;
  dispute_id: string;
  id: Generated<string>;
  raised_at: Generated<Timestamp>;
  raised_by: string;
  status: Generated<string>;
}

export interface Escalation {
  actor: EscalationActor;
  checkpoint: string | null;
  escalated_at: Timestamp | null;
  id: Generated<string>;
  order_id: string;
  outcome: string | null;
  reminder_sent_at: Timestamp | null;
  resolved_at: Timestamp | null;
}

export interface ExternalSupplier {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  legal_name: string;
  license_number: string | null;
  order_id: string;
  verification_source: string | null;
  vetted_at: Timestamp | null;
  vetted_by: string | null;
  vetting_status: Generated<VettingStatus>;
  years_active: number | null;
}

export interface FinancialApproval {
  action: string;
  approved_at: Timestamp | null;
  approver_id: string;
  entity_id: string;
  entity_type: string;
  id: Generated<string>;
  submitted_at: Generated<Timestamp>;
  submitter_id: string;
}

export interface Offer {
  admin_review_status: Generated<string>;
  fob_value_usd: Numeric;
  id: Generated<string>;
  lead_time_days: number | null;
  order_id: string;
  registered_supplier_id: string;
  submitted_at: Generated<Timestamp>;
  terms: string | null;
}

export interface Order {
  active_dispute_id: string | null;
  active_escalation_id: string | null;
  created_at: Generated<Timestamp>;
  current_state: Generated<OrderState>;
  customer_id: string;
  external_supplier_id: string | null;
  final_value_sar: Numeric | null;
  financial_commitment_started_at: Timestamp | null;
  fob_value_usd: Numeric | null;
  fx_rate_deviation_approved_at: Timestamp | null;
  fx_rate_deviation_approved_by: string | null;
  fx_rate_deviation_flag: Generated<boolean>;
  fx_rate_entered_by: string | null;
  fx_rate_source: string | null;
  fx_rate_used: Numeric | null;
  hold_type: Generated<HoldType>;
  id: Generated<string>;
  low_competition_offer: Generated<boolean>;
  registered_supplier_id: string | null;
  resume_target_state: string | null;
  service_type_id: string;
  state_version: Generated<number>;
  supplier_type: Generated<SupplierType>;
}

export interface Payment {
  amount_sar: Numeric;
  created_at: Generated<Timestamp>;
  current_refundability_status: Generated<RefundabilityStatus>;
  id: Generated<string>;
  installment_id: string;
  paid_at: Timestamp | null;
  refund_policy: RefundPolicy;
}

export interface PaymentInstallment {
  due_stage: OrderState | null;
  expected_amount_sar: Numeric;
  id: Generated<string>;
  is_trust_fund: boolean;
  label: string;
  payment_plan_id: string;
  refund_policy: RefundPolicy;
  sequence_no: number;
  unique_payment_reference: string;
}

export interface PaymentPlan {
  contract_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  total_installments: number;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface ProductionUpdate {
  content: string | null;
  file_url: string | null;
  id: Generated<string>;
  kind: string;
  order_id: string;
  posted_at: Generated<Timestamp>;
  posted_by: string;
}

export interface Receipt {
  amount_claimed: Numeric;
  bank_name: string | null;
  bank_reference_no: string;
  file_url: string;
  id: Generated<string>;
  ocr_extracted_fields: Json | null;
  payment_id: string;
  perceptual_hash: string | null;
  receipt_fingerprint: string;
  rejection_reason: string | null;
  transfer_date_claimed: Timestamp;
  verification_status: Generated<string>;
  verified_at: Timestamp | null;
  verified_by: string | null;
}

export interface RefundTransaction {
  decided_at: Generated<Timestamp>;
  decided_by_accountant: string;
  decided_by_owner: string;
  dispute_id: string | null;
  id: Generated<string>;
  payment_id: string;
  reason: string;
  refund_ratio: Numeric | null;
  refunded_amount_sar: Numeric;
}

export interface RegisteredSupplier {
  bank_account_ref: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  legal_name: string;
}

export interface SalaryAccrual {
  accrued_amount_sar: Numeric;
  employee_ref: string;
  id: Generated<string>;
  is_actually_disbursed: Generated<boolean>;
  period: Timestamp;
}

export interface ScheduledTimer {
  cancelled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expected_state_version: number;
  fired_at: Timestamp | null;
  id: Generated<string>;
  order_id: string;
  pg_boss_job_id: string | null;
  run_at: Timestamp;
  timer_type: string;
}

export interface ServiceType {
  code: string;
  commission_rate_percent: Numeric;
  description_excluded_ar: string | null;
  description_included_ar: string | null;
  id: Generated<string>;
  includes_customs_clearance: Generated<boolean>;
  includes_identity_management: boolean;
  includes_production_oversight: boolean;
  includes_sourcing: boolean;
  is_active: Generated<boolean>;
  label_ar: string;
}

export interface ShippingDocument {
  doc_type: string;
  file_url: string;
  id: Generated<string>;
  order_id: string;
  uploaded_at: Generated<Timestamp>;
  uploaded_by: string | null;
}

export interface StateTransitionLog {
  acted_by_id: string | null;
  acted_by_role: string;
  entered_at: Generated<Timestamp>;
  event: string;
  exited_at: Timestamp | null;
  from_state: OrderState | null;
  id: Generated<Int8>;
  order_id: string;
  payload: Json | null;
  to_state: OrderState;
}

export interface SupplierCategory {
  id: Generated<string>;
  name: string;
}

export interface SupplierCategoryMap {
  registered_supplier_id: string;
  supplier_category_id: string;
}

export interface SupplierRating {
  created_at: Generated<Timestamp>;
  external_supplier_id: string | null;
  id: Generated<string>;
  notes: string | null;
  order_id: string | null;
  phase: RatingPhase;
  rated_by: string;
  registered_supplier_id: string | null;
  score: number;
  supplier_type: SupplierType;
}

export interface DB {
  admin_user: AdminUser;
  agreement_renewal: AgreementRenewal;
  audit_log: AuditLog;
  bidding_board: BiddingBoard;
  company_expense: CompanyExpense;
  contract: Contract;
  customer: Customer;
  customs_fee: CustomsFee;
  dispute: Dispute;
  dispute_claim: DisputeClaim;
  escalation: Escalation;
  external_supplier: ExternalSupplier;
  financial_approval: FinancialApproval;
  offer: Offer;
  order: Order;
  payment: Payment;
  payment_installment: PaymentInstallment;
  payment_plan: PaymentPlan;
  pgmigrations: Pgmigrations;
  production_update: ProductionUpdate;
  receipt: Receipt;
  refund_transaction: RefundTransaction;
  registered_supplier: RegisteredSupplier;
  salary_accrual: SalaryAccrual;
  scheduled_timer: ScheduledTimer;
  service_type: ServiceType;
  shipping_document: ShippingDocument;
  state_transition_log: StateTransitionLog;
  supplier_category: SupplierCategory;
  supplier_category_map: SupplierCategoryMap;
  supplier_rating: SupplierRating;
}
